### ISSUE TITLE
[P1] Build the full dependency graph before create-knex-app and doctor

### ISSUE THREAD

**Issue by executionreverted** [rootkeystudio/k-nex-platform-core#38]
Found during the 2026-09-22 product-readiness audit of `main@bf2136359edb7632fdadd5b8aebc63527fb06287`. This issue describes the audited main commit; unmerged PRs are not treated as delivered fixes.

The root commands build a manually selected package list. `create-knex-app` builds contracts, composition and runtime, but runtime now imports `@k-nex/extension-bundler` from its executable-closure verifier. A clean checkout has no bundler dist to resolve. `doctor` also omits transitive prerequisites.

Evidence: [package.json:22](https://github.com/rootkeystudio/k-nex-platform-core/blob/bf2136359edb7632fdadd5b8aebc63527fb06287/package.json#L22), [packages/runtime/src/generated-executable-closure.ts:5](https://github.com/rootkeystudio/k-nex-platform-core/blob/bf2136359edb7632fdadd5b8aebc63527fb06287/packages/runtime/src/generated-executable-closure.ts#L5). An isolated cold-build reproduction using the actual runtime sources/config, built contracts/composition, and the bundler manifest without dist fails with `TS2307 Cannot find module '@k-nex/extension-bundler'`. A preceding root `pnpm build` hides the problem. This reproduction tests the compiler boundary, not a completed customer installation.

Acceptance:
- Build the selected command's transitive workspace dependencies in dependency order.
- From a clean checkout with no dist/cache, frozen install followed directly by the documented create command reaches generation without an undeclared preparatory full build.
- Add the same clean-output smoke for doctor; distinguish missing customer prerequisites from CLI build failure.

The attestation failure already covered by #36/#37 is a separate later blocker.
